services:
  - type: web
    name: mqs-quiz-app
    runtime: php
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: SMTP_HOST
        value: smtp.mailgun.org
      - key: SMTP_USERNAME
        value: postmaster@sandbox36627b5b68c94312b8e418009a7ece4f.mailgun.org
      - key: SMTP_PASSWORD
        value: YOUR_MAILGUN_API_KEY_HERE
      - key: SMTP_PORT
        value: 587
    staticPublishPath: ""
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: index.php
